"""Amortised 4x super-resolution with a conditional TarFlow adapter: the objective ablation.

The operator downsamples a 32x32 image to 8x8 by bicubic interpolation with antialiasing,
and y = op(x) + SIG*eps with SIG = 0.05, giving a residual floor of 0.693. The adapter is
the TarFlow of tarflow_adapter.py, conditioned on the observation through a small CNN whose
output is added at each block.

Three objectives are available, chosen by the OBJ environment variable. Training
observations are generated by the flow map rather than taken from real images, because the
forward-KL objective needs exact pairs of noise and observation.

OBJ=fkl trains by maximum likelihood on fresh pairs. OBJ=rkl trains by reverse KL alone,
using the sticking-the-landing estimator. OBJ=mix adds a reverse-KL term to the
forward-KL one, with a weight that is zero for the first 6k steps and is then raised so
that the reverse-KL term contributes 5, 15, 40 and 55 per cent of the total gradient at
steps 6000, 7000, 8500 and 10000.

All three arms share a fixed validation set of 1000 real CIFAR test images, and report
residual, pixel-space CRPS and the latent norm.
"""
import copy, json, math, os, sys, time
import torch
import torch.nn as nn
import torch.nn.functional as F

# repo layout: shared modules live in common/
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "common"))
from flow_map import decode1, decode1_diff, save_grid, COMMON, D, device
sys.path.insert(0, f"{COMMON}/ml-tarflow")
from transformer_flow import Model

OBJ = os.environ.get("OBJ", "fkl")  # fkl | mix | rkl
NAME = os.environ.get("NAME", f"SRT_{OBJ}")
SIG = 0.05
STEPS = int(os.environ.get("STEPS", "6000" if OBJ == "rkl" else "12000"))
BATCH = int(os.environ.get("BATCH", "32" if OBJ == "rkl" else "128"))
ACC = int(os.environ.get("ACC", "2" if OBJ == "rkl" else "1"))
RKLB = int(os.environ.get("RKLB", "32"))
LR = float(os.environ.get("LR", "2e-4" if OBJ == "rkl" else "5e-4"))
DIAG_AT = int(os.environ.get("DIAG_AT", "6000"))
VAL_N = int(os.environ.get("VAL_N", "1000"))
K_VAL = int(os.environ.get("K_VAL", "10"))
SEED = int(os.environ.get("SEED", "0"))
torch.manual_seed(SEED)
TOK, PDIM, CH, NB = 64, 48, 256, 4
RES_FLOOR = SIG * math.sqrt(8 * 8 * 3)


def op(x):
    return F.interpolate(x, size=8, mode="bicubic", antialias=True)


def reward(x, y):
    return -((op(x) - y) ** 2).flatten(1).sum(1) / (2 * SIG ** 2)


def logN_img(z_img):
    return -0.5 * z_img.flatten(1).pow(2).sum(-1) - 0.5 * D * math.log(2 * math.pi)


# model
q = Model(in_channels=3, img_size=32, patch_size=4, channels=CH,
          num_blocks=NB, layers_per_block=2, nvp=True, num_classes=0).to(device)
for b in q.blocks:
    nn.init.zeros_(b.proj_out.bias)

class CondPath(nn.Module):
    """SR-champion conditioning: same-res CNN on the 8x8 observation -> 64 tokens (1:1
    with the patch grid) -> per-block Linear, added in the class-embed slot."""
    def __init__(self):
        super().__init__()
        self.enc = nn.Sequential(
            nn.Conv2d(3, 64, 3, padding=1), nn.SiLU(),
            nn.Conv2d(64, 64, 3, padding=1), nn.SiLU(),
            nn.Conv2d(64, 64, 3, padding=1))
        self.proj = nn.ModuleList([nn.Linear(64, CH) for _ in range(NB)])
    def forward(self, y):
        t = self.enc(y).flatten(2).transpose(1, 2)  # (B, 64tok, 64)
        return [p(t) for p in self.proj]

cond = CondPath().to(device)
params = list(q.parameters()) + list(cond.parameters())
n_par = sum(p.numel() for p in params)
print(f"{NAME}: OBJ={OBJ} cond-tarflow patch4 ch{CH} nb{NB}x2 + SR CondPath, params {n_par/1e6:.2f}M | "
      f"lr {LR} cosine, batch {BATCH}x{ACC}, {STEPS} steps | floor {RES_FLOOR:.3f}", flush=True)

_tq, _tc = copy.deepcopy(q), copy.deepcopy(cond)  # STL twins (rkl / mix rkl-term)
for m in (_tq, _tc):
    for p_ in m.parameters():
        p_.requires_grad_(False)

def refresh_twins():
    _tq.load_state_dict(q.state_dict()); _tc.load_state_dict(cond.state_dict())


def block_fwd(blk, x, ce):
    xp = blk.permutation(x)
    pos = blk.permutation(blk.pos_embed, dim=0)
    cep = blk.permutation(ce, dim=1)
    x_in = xp
    h = blk.proj_in(xp) + pos + cep
    for ab in blk.attn_blocks:
        h = ab(h, blk.attn_mask)
    ho = blk.proj_out(h)
    ho = torch.cat([torch.zeros_like(ho[:, :1]), ho[:, :-1]], dim=1)
    xa, xb = ho.chunk(2, dim=-1)
    out = (x_in - xb) * (-xa.float()).exp().type(xa.dtype)
    return blk.permutation(out, inverse=True), -xa.mean(dim=[1, 2])


def logprob(mq, mc, z_img, y):
    ces = mc(y)
    x = mq.patchify(z_img)
    logdet = torch.zeros(x.shape[0], device=device)
    for blk, ce in zip(mq.blocks, ces):
        x, ld = block_fwd(blk, x, ce)
        logdet = logdet + ld * D
    return logN_img(mq.unpatchify(x)) + logdet


def sample_diff(n, y):
    """conditional differentiable sequential sampler (no log-det: STL handles entropy)."""
    ces = cond(y)
    x = torch.randn(n, TOK, PDIM, device=device)
    for blk, ce in zip(reversed(list(q.blocks)), reversed(ces)):
        xp = blk.permutation(x)
        pos = blk.permutation(blk.pos_embed, dim=0)
        cep = blk.permutation(ce, dim=1)
        T = xp.shape[1]
        for i in range(T - 1):
            mask = torch.tril(torch.ones(i + 1, i + 1, device=device))
            h = blk.proj_in(xp[:, :i + 1]) + pos[:i + 1] + cep[:, :i + 1]
            for ab in blk.attn_blocks:
                h = ab(h, mask)
            xa, xb = blk.proj_out(h)[:, i:i + 1].chunk(2, dim=-1)
            nxt = xp[:, i + 1:i + 2] * xa[:, 0:1].float().exp().type(xa.dtype) + xb[:, 0:1]
            xp = torch.cat([xp[:, :i + 1], nxt, xp[:, i + 2:]], dim=1)
        x = blk.permutation(xp, inverse=True)
    return q.unpatchify(x)


@torch.no_grad()
def sample(n, y, bs=1000):
    out = []
    for i in range(0, n, bs):
        k = min(bs, n - i)
        out.append(sample_diff(k, y[i:i+k]))
    return torch.cat(out)


# fixed validation set: 1000 real test images
from torchvision import datasets
import torchvision.transforms.functional as TF
_ds = datasets.CIFAR10(f"{COMMON}/cifar_data", train=False, download=False)
g_v = torch.Generator().manual_seed(4242)
VIDX = torch.randperm(10000, generator=g_v)[:VAL_N].tolist()
X_VAL = torch.stack([TF.to_tensor(_ds[j][0]) * 2 - 1 for j in VIDX]).to(device)
g_n = torch.Generator().manual_seed(4243)
Y_VAL = op(X_VAL) + SIG * torch.randn(VAL_N, 3, 8, 8, generator=g_n).to(device)


@torch.no_grad()
def val_residual(k=1):
    z = sample(VAL_N, Y_VAL)
    x = decode1(z.flatten(1))
    res = ((op(x) - Y_VAL) ** 2).flatten(1).sum(1).sqrt().mean()
    zn = z.flatten(1).norm(dim=1).mean()
    return float(res), float(zn)


@torch.no_grad()
def val_full():
    """K_VAL samples/target: residual over all, pixel-space CRPS (unbiased), znorm."""
    xs, res_sum, zn_sum = [], 0.0, 0.0
    for _ in range(K_VAL):
        z = sample(VAL_N, Y_VAL)
        x = decode1(z.flatten(1))
        res_sum += float(((op(x) - Y_VAL) ** 2).flatten(1).sum(1).sqrt().mean())
        zn_sum += float(z.flatten(1).norm(dim=1).mean())
        xs.append(x.half().cpu())
    X = torch.stack(xs, dim=1)  # (VAL_N, K, 3, 32, 32) fp16 cpu
    crps_sum, nchunk = 0.0, 0
    for i in range(0, VAL_N, 100):
        Xi = X[i:i+100].to(device).float().flatten(2)  # (n, K, 3072)
        xt = X_VAL[i:i+100].flatten(1).unsqueeze(1)  # (n, 1, 3072)
        t1 = (Xi - xt).abs().mean(dim=(1, 2))  # mean_k |X - x*|
        pair = (Xi.unsqueeze(1) - Xi.unsqueeze(2)).abs()  # (n, K, K, 3072)
        K = Xi.shape[1]
        t2 = pair.sum(dim=(1, 2)).mean(1) / (2 * K * (K - 1))  # unbiased spread term
        crps_sum += float((t1 - t2).sum()); nchunk += Xi.shape[0]
    return res_sum / K_VAL, crps_sum / nchunk, zn_sum / K_VAL


def hist_append(rec):
    with open(f"{COMMON}/SRT_{NAME}_hist.jsonl", "a") as f:
        f.write(json.dumps(rec) + "\n")


def save_ckpt(path):
    torch.save({"q": q.state_dict(), "cond": cond.state_dict()}, path)


# losses
def fkl_loss(nb):
    with torch.no_grad():
        zt = torch.randn(nb, D, device=device)
        xt = decode1(zt)
        y = op(xt) + SIG * torch.randn(nb, 3, 8, 8, device=device)
    return -(logprob(q, cond, zt.view(nb, 3, 32, 32), y)).mean(), y


def rkl_loss(nb, y):
    z = sample_diff(nb, y)
    lq = logprob(_tq, _tc, z, y)  # STL: parameter-detached twins
    return (lq - logN_img(z) - reward(decode1_diff(z.flatten(1)), y)).mean()


def grad_norm_of(loss):
    gs = torch.autograd.grad(loss, params, retain_graph=False, allow_unused=True)
    return float(torch.sqrt(sum((g.float() ** 2).sum() for g in gs if g is not None)))


# training
opt = torch.optim.Adam(params, lr=LR)
sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=STEPS, eta_min=1e-5)
best = {"res": float("inf"), "res_step": 0, "crps": float("inf"), "crps_step": 0}
WS = []  # mix ladder: [(step, w)]
def w_of(step):
    w = 0.0
    for s, v in WS:
        if step >= s:
            w = v
    return w

t0 = time.time()
for i in range(1, STEPS + 1):
    opt.zero_grad(set_to_none=True)
    if OBJ == "fkl":
        loss, _ = fkl_loss(BATCH)
        loss.backward(); loss_val = float(loss)
    elif OBJ == "rkl":
        refresh_twins(); loss_val = 0.0
        for _a in range(ACC):
            with torch.no_grad():
                yb = op(decode1(torch.randn(BATCH, D, device=device))) + SIG * torch.randn(BATCH, 3, 8, 8, device=device)
            l = rkl_loss(BATCH, yb) / ACC
            l.backward(); loss_val += float(l) * ACC
    else:  # mix
        w = w_of(i)
        lf, y = fkl_loss(BATCH)
        if w > 0:
            refresh_twins()
            loss = lf + w * rkl_loss(RKLB, y[:RKLB])
        else:
            loss = lf
        loss.backward(); loss_val = float(loss)
    torch.nn.utils.clip_grad_norm_(params, 5.0)
    opt.step(); sched.step()
    if not math.isfinite(loss_val):
        print(f"NaN at {i} - abort", flush=True); raise SystemExit(3)

    if OBJ == "mix" and i == DIAG_AT:  # calibrate the ladder at the NPE end
        save_ckpt(f"{COMMON}/SRT_{NAME}_npe_end.pt")
        gf, gr = [], []
        for _ in range(4):
            lf, y = fkl_loss(BATCH)
            gf.append(grad_norm_of(lf))
            refresh_twins()
            gr.append(grad_norm_of(rkl_loss(RKLB, y[:RKLB])))
        R = (sum(gr) / 4) / (sum(gf) / 4)
        WS = [(DIAG_AT, 0.05), (DIAG_AT + 1000, 0.15), (DIAG_AT + 2500, 0.40), (DIAG_AT + 4000, 0.55)]
        WS = [(s, (sh / (1 - sh)) / R) for s, sh in WS]
        print(f"DIAG@{i}: |g_fkl| {sum(gf)/4:.1f} |g_rkl| {sum(gr)/4:.1f} R {R:.0f} -> "
              f"WSCHED {[(s, round(v, 7)) for s, v in WS]}", flush=True)

    if i % 250 == 0:
        r1, zn = val_residual()
        rec = {"step": i, "res1": round(r1, 4), "znorm": round(zn, 2),
               "w": w_of(i) if OBJ == "mix" else None, "min": round((time.time()-t0)/60, 1)}
        line = f"{NAME} {i}: val_res {r1:.4f} znorm {zn:.1f} ({rec['min']}m)"
        if i % 1000 == 0:
            rk, crps, znf = val_full()
            rec.update({"res10": round(rk, 4), "crps": round(crps, 4)})
            line += f" | res10 {rk:.4f} CRPS {crps:.4f}"
            if rk < best["res"]:
                best.update({"res": rk, "res_step": i}); save_ckpt(f"{COMMON}/SRT_{NAME}_bestres.pt"); line += " <-- best-res"
            if crps < best["crps"]:
                best.update({"crps": crps, "crps_step": i}); save_ckpt(f"{COMMON}/SRT_{NAME}_bestcrps.pt"); line += " <-- best-crps"
        hist_append(rec)
        print(line, flush=True)
    if os.environ.get("SMOKE") == "1" and i >= int(os.environ.get("SMOKE_STEPS", "3")):
        print(f"SMOKE OK (peak mem {torch.cuda.max_memory_allocated()/2**30:.1f} GiB)", flush=True)
        raise SystemExit

save_ckpt(f"{COMMON}/SRT_{NAME}.pt")
rk, crps, znf = val_full()
mins = (time.time() - t0) / 60
row = {"name": NAME, "obj": OBJ, "steps": STEPS, "minutes": round(mins, 1), "params_M": round(n_par/1e6, 2),
       "lr": LR, "batch": f"{BATCH}x{ACC}", "rklb": RKLB if OBJ == "mix" else None,
       "final_res10": round(rk, 4), "final_crps": round(crps, 4), "final_znorm": round(znf, 2),
       "res_floor": round(RES_FLOOR, 4), "best_res": {k: best[k] for k in ("res", "res_step")},
       "best_crps": {k: best[k] for k in ("crps", "crps_step")},
       "wsched": [(s, round(v, 7)) for s, v in WS] if OBJ == "mix" else None,
       "val": {"n": VAL_N, "k": K_VAL, "source": "real test, seed 4242/4243"}}
json.dump(row, open(f"{COMMON}/SRT_{NAME}_row.json", "w"), indent=1)
with torch.no_grad():  # 8-target x 10-sample figure
    rows = []
    gap = torch.ones(3, 32, 2, device=device)
    for t in range(8):
        zs = sample(10, Y_VAL[t:t+1].expand(10, -1, -1, -1))
        xs = decode1(zs.flatten(1))
        yup = F.interpolate(Y_VAL[t:t+1], size=32, mode="nearest")[0]
        rows.append(torch.cat([X_VAL[t], yup, gap] + [xs[j] for j in range(10)], dim=2))
    strip = torch.cat(rows, dim=1)
    save_grid(strip.unsqueeze(0), f"{COMMON}/SRT_{NAME}_grid.png", nrow=1)
print(f"EVAL {NAME}: res10 {rk:.4f} (floor {RES_FLOOR:.3f}) CRPS {crps:.4f} znorm {znf:.1f} "
      f"| best_res {best['res']:.4f}@{best['res_step']} best_crps {best['crps']:.4f}@{best['crps_step']} "
      f"| {mins:.1f} min", flush=True)
print(f"ARM {NAME} DONE", flush=True)
